import { Callout } from "../../components/docs/Callout";

export default function VoiceMode() {
    return (
        <>
            <p className="text-sm text-slate-500 mb-6">Last updated: Oct 24, 2024</p>
            <h1>Voice Mode</h1>

            <p>
                Typing out complex emotions can often feel exhausting. Voice Mode allows you to interact with the MindBridge AI hands-free, making the app much more accessible during moments of high anxiety or panic.
            </p>

            <h2 id="how-to-use-voice-input">How to use voice input</h2>
            <p>
                On the Chat Page, you will find a Microphone icon next to the "Send" button in the input bar.
            </p>
            <ol>
                <li>Tap the Microphone. A red pulse indicator will appear, letting you know the browser is actively listening.</li>
                <li>Speak naturally into your device's microphone.</li>
                <li>When you stop speaking, the Web Speech API automatically finalizes the transcription and sends it to the AI.</li>
            </ol>

            <h2 id="voice-output">Voice output / Text-to-Speech</h2>
            <p>
                To complete the hands-free loop, MindBridge includes a <strong>Speaker icon</strong> toggle. When enabled, every response generated by Gemini is immediately synthesized into speech and read aloud.
            </p>
            <p>
                We specifically filter out markdown characters (like `**` bolding or `[CRISIS]` tags) before passing the string to the speech synthesizer, ensuring a smooth, natural-sounding playback.
            </p>

            <h2 id="browser-compatibility">Browser compatibility</h2>
            <Callout type="info" title="Browser Limitations">
                The Web Speech API (specifically <code>SpeechRecognition</code>) is currently only fully supported and reliable on <strong>Google Chrome</strong>, <strong>Microsoft Edge</strong>, and <strong>Safari</strong> (latest versions). If you access MindBridge on Firefox or an older browser, the microphone button will gracefully disable itself, but text chat will remain fully functional.
            </Callout>
        </>
    );
}
