import { Callout } from "../../components/docs/Callout";
import { useLanguage } from "../../context/LanguageContext";

const content = {
  en: {
    lastUpdated: "Last updated: Oct 24, 2024",
    h1: "Voice Mode",
    intro: "Typing out complex emotions can often feel exhausting. Voice Mode allows you to interact with the MindBridge AI hands-free, making the app much more accessible during moments of high anxiety or panic.",
    inputH2: "How to use voice input",
    inputP: "On the Chat Page, you will find a Microphone icon next to the \"Send\" button in the input bar.",
    inputSteps: ["Tap the Microphone. A red pulse indicator will appear, letting you know the browser is actively listening.", "Speak naturally into your device's microphone.", "When you stop speaking, the Web Speech API automatically finalizes the transcription and sends it to the AI."],
    outputH2: "Voice output / Text-to-Speech",
    outputP1: <>To complete the hands-free loop, MindBridge includes a <strong>Speaker icon</strong> toggle. When enabled, every response generated by Gemini is immediately synthesized into speech and read aloud.</>,
    outputP2: <>We specifically filter out markdown characters (like <code>**</code> bolding or <code>[CRISIS]</code> tags) before passing the string to the speech synthesizer, ensuring a smooth, natural-sounding playback.</>,
    compatH2: "Browser compatibility",
    calloutTitle: "Browser Limitations",
    calloutText: <>The Web Speech API (specifically <code>SpeechRecognition</code>) is currently only fully supported and reliable on <strong>Google Chrome</strong>, <strong>Microsoft Edge</strong>, and <strong>Safari</strong> (latest versions). If you access MindBridge on Firefox or an older browser, the microphone button will gracefully disable itself, but text chat will remain fully functional.</>,
  },
  hi: {
    lastUpdated: "अंतिम अपडेट: अक्टू. 24, 2024",
    h1: "वॉइस मोड",
    intro: "जटिल भावनाओं को टाइप करना अक्सर थकाऊ लग सकता है। वॉइस मोड आपको MindBridge AI के साथ हैंड्स-फ्री इंटरैक्ट करने देता है, जिससे उच्च चिंता या घबराहट के क्षणों में ऐप बहुत अधिक सुलभ हो जाता है।",
    inputH2: "वॉइस इनपुट कैसे उपयोग करें",
    inputP: "चैट पेज पर, आपको इनपुट बार में \"भेजें\" बटन के बगल में माइक्रोफ़ोन आइकन मिलेगा।",
    inputSteps: ["माइक्रोफ़ोन टैप करें। एक लाल पल्स इंडिकेटर दिखाई देगा, यह बताते हुए कि ब्राउज़र सक्रिय रूप से सुन रहा है।", "अपने डिवाइस के माइक्रोफ़ोन में स्वाभाविक रूप से बोलें।", "जब आप बोलना बंद करते हैं, Web Speech API स्वचालित रूप से ट्रांसक्रिप्शन को अंतिम रूप देता है और AI को भेजता है।"],
    outputH2: "वॉइस आउटपुट / टेक्स्ट-टू-स्पीच",
    outputP1: <>हैंड्स-फ्री लूप पूरा करने के लिए, MindBridge में एक <strong>स्पीकर आइकन</strong> टॉगल है। जब सक्षम होता है, Gemini द्वारा उत्पन्न हर प्रतिक्रिया तुरंत स्पीच में संश्लेषित होती है और ज़ोर से पढ़ी जाती है।</>,
    outputP2: <>हम स्पीच सिंथेसाइज़र को स्ट्रिंग पास करने से पहले मार्कडाउन अक्षरों (जैसे <code>**</code> बोल्डिंग या <code>[CRISIS]</code> टैग) को विशिष्ट रूप से फिल्टर करते हैं, जिससे स्मूद, प्राकृतिक-सुनाई देने वाला प्लेबैक सुनिश्चित होता है।</>,
    compatH2: "ब्राउज़र संगतता",
    calloutTitle: "ब्राउज़र सीमाएं",
    calloutText: <>Web Speech API (विशेष रूप से <code>SpeechRecognition</code>) वर्तमान में केवल <strong>Google Chrome</strong>, <strong>Microsoft Edge</strong>, और <strong>Safari</strong> (नवीनतम संस्करण) पर पूरी तरह समर्थित और विश्वसनीय है। यदि आप Firefox या पुराने ब्राउज़र पर MindBridge एक्सेस करते हैं, तो माइक्रोफ़ोन बटन खुद को अक्षम कर देगा, लेकिन टेक्स्ट चैट पूरी तरह काम करती रहेगी।</>,
  },
  mr: {
    lastUpdated: "शेवटचे अपडेट: ऑक्टो. 24, 2024",
    h1: "व्हॉइस मोड",
    intro: "जटिल भावना टाइप करणे अनेकदा थकवणारे वाटू शकते. व्हॉइस मोड तुम्हाला MindBridge AI शी हँड्स-फ्री संवाद साधण्यास अनुमती देतो, जे उच्च चिंता किंवा घबराटीच्या क्षणात ॲपला खूप अधिक सुलभ बनवते.",
    inputH2: "व्हॉइस इनपुट कसा वापरायचा",
    inputP: "चॅट पेजवर, तुम्हाला इनपुट बारमध्ये \"पाठवा\" बटणाजवळ मायक्रोफोन आयकन सापडेल.",
    inputSteps: ["मायक्रोफोन टॅप करा. एक लाल पल्स इंडिकेटर दिसेल, ब्राउझर सक्रियपणे ऐकत असल्याचे सांगतो.", "तुमच्या डिव्हाइसच्या मायक्रोफोनमध्ये नैसर्गिकपणे बोला.", "तुम्ही बोलणे थांबवल्यावर, Web Speech API आपोआप ट्रान्सक्रिप्शन पूर्ण करतो आणि AI ला पाठवतो."],
    outputH2: "व्हॉइस आउटपुट / टेक्स्ट-टू-स्पीच",
    outputP1: <>हँड्स-फ्री लूप पूर्ण करण्यासाठी, MindBridge मध्ये एक <strong>स्पीकर आयकन</strong> टॉगल आहे. सक्रिय असताना, Gemini द्वारे तयार केलेला प्रत्येक प्रतिसाद त्वरित स्पीचमध्ये संश्लेषित होतो आणि मोठ्याने वाचला जातो.</>,
    outputP2: <>आम्ही स्पीच सिंथेसायझरला स्ट्रिंग पास करण्यापूर्वी मार्कडाउन वर्ण (जसे <code>**</code> बोल्डिंग किंवा <code>[CRISIS]</code> टॅग) विशेषत: फिल्टर करतो, गुळगुळीत, नैसर्गिक-वाटणारे प्लेबॅक सुनिश्चित करतो.</>,
    compatH2: "ब्राउझर सुसंगतता",
    calloutTitle: "ब्राउझर मर्यादा",
    calloutText: <>Web Speech API (विशेषतः <code>SpeechRecognition</code>) सध्या फक्त <strong>Google Chrome</strong>, <strong>Microsoft Edge</strong>, आणि <strong>Safari</strong> (नवीनतम आवृत्त्या) वर पूर्णपणे समर्थित आणि विश्वसनीय आहे. तुम्ही Firefox किंवा जुन्या ब्राउझरवर MindBridge ऍक्सेस केल्यास, मायक्रोफोन बटण स्वतः बंद होईल, परंतु टेक्स्ट चॅट पूर्णपणे कार्यरत राहील.</>,
  },
};

export default function VoiceMode() {
  const { lang } = useLanguage();
  const c = content[lang] || content.en;

  return (
    <>
      <p className="text-sm text-slate-500 mb-6">{c.lastUpdated}</p>
      <h1>{c.h1}</h1>

      <p>{c.intro}</p>

      <h2 id="how-to-use-voice-input">{c.inputH2}</h2>
      <p>{c.inputP}</p>
      <ol>
        {c.inputSteps.map((step, i) => <li key={i}>{step}</li>)}
      </ol>

      <h2 id="voice-output">{c.outputH2}</h2>
      <p>{c.outputP1}</p>
      <p>{c.outputP2}</p>

      <h2 id="browser-compatibility">{c.compatH2}</h2>
      <Callout type="info" title={c.calloutTitle}>
        {c.calloutText}
      </Callout>
    </>
  );
}
